Check url with locale prefixes and compare with redirectSlug
apostrophecms/redirect pull request #16
Opened 2023-07-24 16:01 UTC by ValJed

[PRO-4495](https://linear.app/apostrophecms/issue/PRO-4495/the-redirect-module-checks-the-slug-property-of-the-redirect-piece)
[PRO-4493](https://linear.app/apostrophecms/issue/PRO-4493/redirectlocalization-issues-prefixes-are-removed-before-consulting)

## Summary
* Modifies the middleware to check the `originalUrl` instead of `url` in which the locale prefix has been removed.
* Removes the regex and performs a `$or` request on redirect pieces `redirectSlug` property because there was issues when using the slug since this one can be modified by the server for de duplication for example.
* When redirecting to internal pages, use the page piece `slug` property instead of the `_url` of the new page to avoid being redirected on pages like `/fr/fr/page`.

## What are the specific steps to test this change?

On project with multiple locales using prefixes, when creating a new redirection, you must specify the locale prefix, it allows to avoid conflicts with potential pieces with the same slug in other locales.

## What kind of change does this PR introduce?

- [X] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [X] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

2023-07-27 15:37 UTC, ValJed commented on index.js
> +            return req.res.redirect(status, target._newPage[0].slug);
Modified to take `target._newPage[0].slug` instead of `target._newPage[0]._url` because I was ended with redirection to pages like `/fr/fr/page` since the locale prefix is automatically added.
No more issue with slug.

2023-07-27 15:43 UTC, ValJed commented on index.js
> +          const results = await self.find(req, { $or: [ { redirectSlug: slug }, { redirectSlug: pathOnly } ] }).toArray();
I get redirections with and without query params. Then I still perform a find on both depending on the `ignoreQueryString` property.
I don't think we need a regex here, or maybe just to remove the last slash?
BTW using `redirectSlug` instead of `slug` here because with the latter it doesn't work when slug is deduplicated, by an archived piece for example.

2023-07-27 16:52 UTC, boutell requested changes

2023-07-27 16:52 UTC, boutell commented on index.js
> +          const results = await self.find(req, { $or: [ { redirectSlug: slug }, { redirectSlug: pathOnly } ] }).toArray();
I'm saying "uncle" here. Using `slug` for speed is just too messy. So please add a mongodb database index on `redirectSlug`. See the doc module for examples.

2023-07-27 16:52 UTC, boutell commented on index.js
> +            return req.res.redirect(status, target._newPage[0].slug);
Use `rawRedirect`.

2023-07-27 16:52 UTC, boutell commented on index.js
> +            return req.res.redirect(status, target.externalUrl);
rawRedirect here too.

2023-08-03 16:36 UTC, boutell commented
Reminder that this request for changes is pending.

2023-08-14 20:47 UTC, boutell requested changes

2023-08-14 20:47 UTC, boutell commented on CHANGELOG.md
> +- Fixes redirections when using locales prefixes. The locale prefix must be added to the `redirectSlug` to avoid conflicts with other locales.
locale prefixes

2023-08-14 20:47 UTC, boutell commented on index.js
> +            .find(req, { $or: [ { redirectSlug: slug }, { redirectSlug: pathOnly } ] })
This may be a slight performance hit, but OK. Time to make this code simple.

2023-08-16 12:38 UTC, ValJed commented on index.js
> +            .find(req, { $or: [ { redirectSlug: slug }, { redirectSlug: pathOnly } ] })
You think it's less efficient than a regex query?
I added an index on `redirectSlug` also.

2023-08-16 13:37 UTC, boutell approved these changes

2023-08-16 13:39 UTC, merged