Pro 4691 redirect to other locales
apostrophecms/redirect pull request #18
Opened 2023-10-17 14:45 UTC by ValJed

[PRO-4691](https://linear.app/apostrophecms/issue/PRO-4691/redirect-to-other-locales-redirect-module)

## Summary

* Allow to redirect to locales that are not the current one by storing (when the target is an internal page is another locale) the `targetLocale` in the redirect document. This way we can update the `req` object based on this information to get the right page relationship, whatever the current locale.
* Add tests for external redirects, internal redirects, and internal redirects to other locales.

* Add a query builder and extend the find method to only get redirects that have external redirect or internal redirect to the current locale.
⚠️ I'm not sure this behavior is viable since it could bring BC for users using the find method of the redirect method. Moreover it will feel unnatural for users to not be able to see all redirects in all locales sinces there are not localized..
For this point I think that we should wait and design a way to properly make it work with relationships. We might need that later in another context.

## What are the specific steps to test this change?

You should be able to redirect a page in `fr` to a page in `en` using internal redirects (relationship will be retrieved based on its locale).

## What kind of change does this PR introduce?

- [X] Bug fix
- [] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [X] The changelog is updated
- [ ] Related documentation has been updated
- [X] Related tests have been updated

2023-10-17 14:47 UTC, ValJed commented on index.js
> +    };
I would not keep this since it might bring weird behavior for users:
* Why I can't see all my redirects in a locale, they aren't localized?
* The find method doesn't return all the redirects anymore, why?

2023-10-17 14:48 UTC, ValJed commented on index.js
> +      builders: {
Based on comment below, I'm not sure this is the right solution here.

2023-10-17 19:49 UTC, boutell requested changes
I do think this is the right approach. We're not in a position time-wise to solve it in a different way right now.

Re: backwards compatibility, the module has been sufficiently broken that I am not concerned. We just need to document the expectations.

However, reading this code over, it seems like you need to move `.withLocaleTarget(req.locale)` to `findForEditing` rather than `find`. Otherwise the `find` call seen in the middleware will fail when the internal document is in another locale, which is what we were trying to prevent. So, please make that change and verify the cross-locale internal page redirects work even when the target locale differs from the default locale, or whatever the locale is going into the middleware.

This will also mitigate the "surprise effect." You will be able to fetch all redirects regardless of the active locale, unless you are editing them, in which case you should not be able to for the reasons we have discussed.

2023-10-18 09:14 UTC, ValJed commented
@boutell Using `findForEditing` isn't working because it's not called to display the list of pieces in the manager modal. It's only called to load a single piece into the editor modal so it would create a very weird UX (visible but impossible to open), which is not good.
I removes the extended method, and made the query builder by default requesting pieces that have to relationships to other locales. It can be disabled by users if needed, I'll document that in the `README`.
I think it should be a major upgrade.

2023-10-18 12:28 UTC, boutell approved these changes
Thanks Etienne. I do not think a major version bump is needed. Here is why: it didn't work before in these cases, and now it does work for the first time, as long as you switch locales, which is a normal pattern for other content types in Apostrophe. I do not think it will be a problem since we have documented it.

2023-10-18 12:28 UTC, boutell commented on README.md
> +It's possible to redirect from a locale to another one, with external redirections,
"from a locale" -> "from one locale"

"since you manually define"

2023-10-18 12:28 UTC, boutell commented on README.md
> +But also with internal redirects (relationship to page), even if relationships don't support relationships to other locales.
As for internal redirects (relationships with pages), this works across locales as well, but keep in mind that you will only see the internal redirects that target the current locale when managing redirects. To find redirects that target an internal page in a different locale, switch locales before viewing "Manage Redirects."

2023-10-18 12:28 UTC, boutell commented on README.md
> +A query builder exist called `currentLocaleTarget` that hide redirects that have relationships to other locales (different from the current one).
A note for developers: a query builder called `currentLocaleTarget` hides redirects that...

2023-10-18 13:29 UTC, boutell approved these changes

2023-10-18 13:47 UTC, boutell approved these changes

2023-10-18 14:07 UTC, merged